- hosts: all
  tasks:
   -  name: make directory
      file:
       path: /home/qainfotech/OCS
       state: directory



   -  name: clone git repository
      git: 
       repo:  https://github.com/OCSInventory-NG/UnixAgent
       dest: /home/qainfotech/OCS
       version: master
      sudo: no
      register: gitstatus
   -  debug:
        msg: "{{gitstatus}}"




   -  name: Update and upgrade apt packages
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      sudo: yes
      register: aptstatus
   -  debug:
        msg: "{{aptstatus}}"



   -  name: installing ocsinventory-agent
      apt:
        name: ocsinventory-agent
        state: present
      sudo: yes
      register: ocsstatus
   -  debug:
        msg: "{{ocsstatus}}"
 


   -  name: configure file
      blockinfile:
       path: /etc/ocsinventory/ocsinventory-agent.cfg
       block: |
         server=http://10.0.1.147/ocsinventory
      sudo: yes
      register: filestatus
   -  debug:
        msg: "{{filestatus}}"


   -  name: Final setup  
      command: "ocsinventory-agent -t Ubuntu http://10.0.1.147/ocsinventory"
      sudo: yes 
      register: status
   -  debug:
       msg: "{{status}}"

